### ISSUE TITLE
script/Snakefile: print(f"number of individual in the distance matrix: {len(delta)}")

### ISSUE THREAD

**Issue by sapfo** [sapfo/medeas#31]
After "installing": 
https://www.cog-genomics.org/plink/1.9/
plink_linux_x86_64_20191028.zip
PLINK v1.90b6.12 64-bit (28 Oct 2019)

and snakemake:
sudo pip3 install snakemake
snakemake 5.7.4

and running: 
snakemake 
under scripts. 

i get: 
File "../main.py", line 41
    print(f"number of individual in the distance matrix: {len(delta)}")
                                                                     ^
SyntaxError: invalid syntax

**Comment by sapfo** [comment]
solved by frederic-michaud
snamake seems to ignore .bashrc defined variables

**Comment by frederic-michaud** [comment]
This error is in general very likely to come from using an old (< 3.6) version of python.
Thanks for reporting.
